#!/usr/bin/env python

from sys import argv


def avg_arithmetic(a, b):
    return 0.5 * (a + b)


def avg_geometric(a, b):
    return (a*b)**0.5


def avg_cubic(a, b):
    x1 = a**3 + b**3
    x2 = a**2 + b**2
    return 1.0 * x1 / x2


def avg_hhg(a, b):
    x1 = 4.0 * a * b
    x2 = a**0.5
    x3 = b**0.5
    return x1 / (x2 + x3)**2


avg_map = {
    'arith': avg_arithmetic,
    'geo': avg_geometric,
    'cubic': avg_cubic,
    'hhg': avg_hhg,
}


def avg_impl():
    func = avg_map[argv[1]]
    a = float(argv[2])
    b = float(argv[3])
    print(func(a, b))


if __name__ == '__main__':
    avg_impl()
